ЭСМБ: выпраўленыя памылкі распазнаваньня
verbumby/slouniki pull request #5
Opened 2024-09-19 15:17 UTC by 375gnu

2024-09-19 15:19 UTC, 375gnu commented
У перамозе выпраўлена "пе-ра‑мога" на "пера‑мога" ў самым канцы.

2024-09-19 15:19 UTC, 375gnu commented
Якое значэньне мае пазнака ◎?

2024-09-19 21:56 UTC, ramanenka requested changes
Вялікі дзякуй! Ці можаш гэтыя памылкі таксама выправіць?


> Якое значэньне мае пазнака ◎?

Не ведаю, гэта было ў арыгінальным файле, я не стаў выдаляць. Хаця, улічваючы, што ў друкаванай версіі такога няма, то можа варта было б выдаліць.

2024-09-19 21:56 UTC, ramanenka commented on esbm/esbm.html
> +<p class="ms-0">◎<strong class="hw" id="lieshuki" style="color: darkblue">Лешукі́</strong> ’лесуны, лясныя нячысцікі’ (<v-abbr class="source">Нік. Няч.</v-abbr>). Рэгіянальнае <v-abbr>бел.</v-abbr> у
```suggestion
<p class="ms-0">◎<strong class="hw" id="lieshuki" style="color: darkblue">Лешукі́</strong> ’лесуны, лясныя нячысцікі’ (<v-abbr class="source">Нік. Няч.</v-abbr>). Рэгіянальнае <v-abbr>бел.</v-abbr> утварэнне з суф. <span style="color: brown">‑ук</span> ад <span style="color: brown">леш-</span> (параўн. <v-abbr>гродз.</v-abbr> <span style="color: brown">ле́шы</span> (<v-abbr class="source">Сл. паўн.-зах.</v-abbr>), <v-abbr>рус.</v-abbr> <span style="color: brown">леший &lt; lěs‑jь</span>).</p>
```

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/07126722-9a59-40a0-b562-dd85a55f25b1">

https://knihi.com/none/Etymalahicny_slounik_bielaruskaj_movy_zip.html#ESBM_05a.djvu_293

2024-09-19 21:56 UTC, ramanenka commented on esbm/esbm.html
> +<p class="ms-0"><strong class="hw" id="pieramoha" style="color: darkblue">Перамо́га</strong> (<span style="color: brown">пірямо́га</span>) ’поспеху змаганні, на вайне; поўны поспех, трыумф’, ’пераадо
`поспеху` -> `поспех у`:
<img width="748" alt="image" src="https://github.com/user-attachments/assets/4b2c2cd7-5c34-4ba6-9f92-58fbf65c4a72">

`przemogą` -> `przemoga`
<img width="397" alt="image" src="https://github.com/user-attachments/assets/dd0880ce-815d-441a-89d5-ce0f7604a609">

`перема́гати се` -> `перемогати се`
<img width="541" alt="image" src="https://github.com/user-attachments/assets/765b0876-5637-454c-a584-18ef73c07ed0">


https://knihi.com/none/Etymalahicny_slounik_bielaruskaj_movy_zip.html#ESBM_09.pdf_63

2024-09-23 11:10 UTC, 375gnu commented
Выправіў. Мне падаецца, што з дапамогай ◎ пазначаныя дрэнна распазнаныя словы. Прынамсі суседзі Лечма́н маюць такія пазнакі, і там таксама трэба выпраўляць. А вось Лешч ня мае, ані пазнакі, ані памылак.

2024-09-23 18:56 UTC, merged